### ISSUE TITLE
Docker image constraints

### ISSUE THREAD

**Issue by hzclarksm** [marius311/boinc-server-docker#18]
I am looking for guidance on how to set some image values so as to facilitate job execution.  Of particular interest are entrypoint, cmd, and workingdir.  How should these be set to allow execution for cases where input files have arbitrary names?   My understanding is that BOINC will manage file transfer and put all input files in a common fixed directory location.  The fixed directory location can then be mounted as a docker volume again at a fixed location.  
  - Can working directory be set to the fixed location inside the docker container?
  - Can entrypoint refer to a script in the working directory? (It would exist in the image)
  - cmd could be used to pass variable arguments to the entrypoint.

Running the command will produce output files.  The documentation implies such outputs should be put in a separate results directory to be transfered back to the BOINC host.  Applications will typically write results in the working directory.  Is there a mechanism to run a post processing script in the container to move results to different location?

**Comment by marius311** [comment]
Yes, so when BOINC runs a job on a client, it does so by default in a folder `slots/N` (where `N` is some some number) inside wherever BOINC is installed on that computer. All input files & executables get copied or linked into this folder. The folder `slots/N/shared` is a special folder mounted inside the Docker container at `/root/shared`. So to use an input file, you need to create a BOINC input file (more on this in a second) and give it an "open name" of `shared/myfile.txt`. The "open name" is where BOINC puts the file relative to `slots/N` meaning it put it at `slots/N/shared/myfile.txt` and it will hence be available inside the container at `/root/shared/myfile.txt`. From there you can do whatever you'd like with it. 

Creating input files for jobs typically involves creating an ["input template"](https://boinc.berkeley.edu/trac/wiki/JobTemplates#Inputtemplates). Its worth reading/understanding how that works, but because boinc2docker adds a number of its own input files (for the purpose of transfering the Docker images to the hosts) you don't use the input template directly the way you would with a traditional job. Instead, you should call the [boinc2docker_create_work](https://github.com/marius311/boinc2docker/blob/68eb80df7d481a0cd727da8939e6cb3385c7edda/bin/boinc2docker_create_work.py#L21) Python function directly, and pass it something in the `input_files` argument. If the contents of your input file was `bar` and you wanted it at `/root/shared/myfile.txt`, you would use `boinc2docker_create_work(...,input_files=[('shared/myfile.txt','bar',[])])`. 

As you'll notice, that Python function is just what gets called when you use `bin/boinc2docker_create_work` from the command line. The difference is you can't specify the input_files via the command line (yet, I'm happy to accept PR on this, and I will get to it at some point), so you have to call the Python directly. That said, I find its often easiest to avoid input files entirely if you can just get away with command line arguments, that way you can use `bin/boinc2docker_create_work`, which accepts arbitrary command line arguments to pass to your container, and you don't have to worry about writing an extra Python script.

On results files, the folder `/root/shared/results` inside the Docker container is automatically tar'ed up and returned to the server, so have your calculations write their results to files in there. From there you handle it just as you would with any regular result file, which means you write a validator to check it and an assimilator to do something with it. There's the simple assimilator pre-installed with boinc-server-docker which just moves things to `/results` on the server which you are free to use, you would add something like this to your config.xml

```xml
        <daemon>
            <cmd>script_assimilator --app camb_boinc2docker --script "boinc2docker_assimilator files"</cmd>
            <pid_file>boinc2docker_assimilator.pid</pid_file>
            <output>boinc2docker_assimilator.log</output>
        </daemon>
```
The validator you'll have to write yourself or use one of the other default ones that come with BOINC. See also https://boinc.berkeley.edu/trac/wiki/ValidationIntro and https://boinc.berkeley.edu/trac/wiki/AssimilateIntro.

**Comment by hzclarksm** [comment]
I was able to modify `bin/boinc2docker_create_work` to treat a very specific case of input file.  For the more general case the difficulty would be how to express the various parameters on the command line.  With that small modification I was able to execute some simple jobs.
Looking ahead I would like to able to use the standard BOINC Python API's for file manipulation and remote job execution. I have run into problems on how to formulate the specification of the files required to create the docker image within the BOINC client.  It seems that  `boinc2docker_create_work` does not employ the typical BOINC hashing scheme for stashing files in the download directory.  The file manipulation API requires the file hash to locate the file in the download directory tree.  A second problem is that I don't see where I can specify where files should be located on the client using the file manipulation API.  
For efficiency sake it would be useful to have the BOINC client download only a single copy of the docker image files.  Is that the case now?

**Comment by marius311** [comment]
> I was able to modify bin/boinc2docker_create_work to treat a very specific case of input file. For the more general case the difficulty would be how to express the various parameters on the command line. With that small modification I was able to execute some simple jobs.

If you could show me these modifications, I might be able to better help. I actually don't think you need any modifications, unless I misunderstood what you're trying to do. 

> For efficiency sake it would be useful to have the BOINC client download only a single copy of the docker image files. Is that the case now?

That's correct. The Docker image is transferred via standard BOINC input files, one layer per input file, and these are marked "sticky" so once the client has them it reuses them for other jobs as needed. 

> Looking ahead I would like to able to use the standard BOINC Python API's for file manipulation and remote job execution. I have run into problems on how to formulate the specification of the files required to create the docker image within the BOINC client. It seems that boinc2docker_create_work does not employ the typical BOINC hashing scheme for stashing files in the download directory. The file manipulation API requires the file hash to locate the file in the download directory tree. A second problem is that I don't see where I can specify where files should be located on the client using the file manipulation API.

Let me give you a definite example that might help. I'm going to create a Docker job that runs a `python:2-alpine` image, which reads and just prints to stdout an input file mounted at `/root/shared/myinput.txt` inside the Docker container, whose contents is going to be `Hello BOINC!`. To do so I first from a fresh instance of `boinc-server-docker`:

```
marius@local:~/workspace/boinc-server-docker$ docker-compose up -d
Creating volume "boincserverdocker_project" with default driver
Creating volume "boincserverdocker_results" with default driver
Creating volume "boincserverdocker_mysql" with default driver
Creating boincserverdocker_mysql_1
Creating boincserverdocker_makeproject_1
Creating boincserverdocker_apache_1
marius@local:~/workspace/boinc-server-docker$ docker exec -it boincserverdocker_apache_1 bash
root@boincserver:~/project#
```

Now, as mentioned above, I have to call `boinc2docker_create_work` from Python, so next I do,

```
root@boincserver:~/project# cd bin/
root@boincserver:~/project/bin# python
Python 2.7.9 (default, Jun 29 2016, 13:08:31) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from boinc2docker_create_work import boinc2docker_create_work
>>> boinc2docker_create_work("python:2-alpine", ["python", "-c", "print open('/root/shared/myinput.txt').read()"], input_files=[("shared/myinput.txt", "Hello BOINC!", [])])
Automatically setting memory allocation for job to 788MB.
Exporting 'python:2-alpine' to tar file...
Creating input file for layer 18445f92472e...
Creating input file for layer e33588723a6c...
Creating input file for layer 322b39d1679e...
Creating input file for image 9c8c07c0f9b7...
Creating input template for job...
'workunit name: boinc2docker_132_1481580866.214213'
>>> 
```

Note the call to `boinc2docker_create_work`, that's where everything is happening. The first two arguments set up the equivalent of `docker run python:2-alpine python -c "print open('/root/shared/myinput.txt').read()`. The `input_files` gives the input file, whose contents I pass a string. If this is some file sitting on the file-system of the server somewhere, you could just do a `open(filename).read()` and pass than instead. 

You can check the input file was created and placed in the BOINC downloads directory, 

```
root@boincserver:~/project# find /root/project/download/ -name *myinput*
/root/project/download/28a/myinput_74f34cf2dcb640bca330e4f1cfce977f.txt
/root/project/download/28a/myinput_74f34cf2dcb640bca330e4f1cfce977f.txt.md5
```

Now connect a client to this server and you should see the job run, containing the following on the log, 

```
2016-12-12 23:15:57 (28698): Guest Log: Waiting for Docker daemon to start...
2016-12-12 23:15:58 (28698): Guest Log: REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
2016-12-12 23:15:58 (28698): Guest Log: Running boinc_app...
2016-12-12 23:15:58 (28698): Guest Log: Importing Docker image from BOINC...
2016-12-12 23:16:01 (28698): Guest Log: Prerun diagnostics...
2016-12-12 23:16:01 (28698): Guest Log: REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
2016-12-12 23:16:01 (28698): Guest Log: python              2-alpine            9c8c07c0f9b7        3 weeks ago         72.25 MB
2016-12-12 23:16:01 (28698): Guest Log: CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
2016-12-12 23:16:01 (28698): Guest Log: 81.1M	/var/lib/docker
2016-12-12 23:16:01 (28698): Guest Log:               total        used        free      shared  buff/cache   available
2016-12-12 23:16:01 (28698): Guest Log: Mem:            761          55         429         245         276         434
2016-12-12 23:16:01 (28698): Guest Log: Swap:           139           0         139
2016-12-12 23:16:01 (28698): Guest Log: Prerun commands...
2016-12-12 23:16:01 (28698): Guest Log: Running... 
2016-12-12 23:16:01 (28698): Guest Log: Hello BOINC!
2016-12-12 23:16:01 (28698): Guest Log: Postrun commands...
2016-12-12 23:16:01 (28698): Guest Log: boinc_app exited (0)
2016-12-12 23:16:01 (28698): Guest Log: Saving results...
```

**Comment by hzclarksm** [comment]
My modifications simply take command line arguments to construct the path to an input file.  From that point on I did as you suggest to add the input to input_files.  What I was trying to say is that it would be complicated to express the required tuple of information on the command line.  It is not necessary for what I am trying to do.

What I am trying to do is marry  `boinc2docker_create_work` with BOINC API as described at [](https://boinc.berkeley.edu/trac/wiki/RemoteJobs) and [](https://boinc.berkeley.edu/trac/wiki/RemoteInputFiles).

**Comment by marius311** [comment]
Ah, I did indeed misunderstand what you're going after. That marriage would be really cool actually, I'd more than welcome a PR if you could make it work.

**Comment by hzclarksm** [comment]
For starters I am trying to separate out the portion of boinc2docker_create_work.py that stages the docker image and layer files into the download directory.  I noticed that you did not use the available bin/stage_file command to do this.  Could you share your reasoning on that?  What is more troubling is that I am unable to determine how you generated the *.md5 files.  I am unable to match the md5 hash contained in *.md5 files.

**Comment by marius311** [comment]
> For starters I am trying to separate out the portion of boinc2docker_create_work.py that stages the docker image and layer files into the download directory

That would be great, the code definitely needs some modularization. 

> I noticed that you did not use the available bin/stage_file command to do this. Could you share your reasoning on that? 

The reason is that with stage_file requires you to write a file to disk, then the bin/stage_file moves it into place in downloads/. Instead I use bin/dir_hier_path to get the target filename in downloads/ first, and write the files directly there (e.g. [here](https://github.com/marius311/boinc2docker/blob/0a7e475f52246da532285b5e81bdbb4e874346c9/bin/boinc2docker_create_work.py#L120))

> What is more troubling is that I am unable to determine how you generated the *.md5 files

Those get generated when I call bin/create_work [here](https://github.com/marius311/boinc2docker/blob/0a7e475f52246da532285b5e81bdbb4e874346c9/py/Boinc/create_work.py#L61)

> I am unable to match the md5 hash contained in *.md5 files.

That's odd. For me, if I call `md5sum` from the command line on any of the generated image or layer files in the downloads directory, I get the exact result in the corresponding .md5 file.

**Comment by hzclarksm** [comment]
It turns out I was only having trouble with one image file.  
I did discover that by default identical files do not produce identical zipped files.  gzip includes a timestamp in the file with the result being that the md5 hash changes.  This can be resolved by adding the --no-name option to the gzip command.

**Comment by hzclarksm** [comment]
More fun with immutable files.
I mentioned last time that gzip incorporates a timestamp into the zipped file.  This means that files zipped at different times will have different hashes and BOINC will not accept more recent copies.
It turns out that tar files also have embedded timestamp information that causes the same problem.  This is relevant because different docker images when decomposed into layer and image file share such files.   I find this to be true  when different docker images built on a common base are decomposed.  I am left with two choices:  use `tar --mtime=XXXX` to unify the time metadata or assume that two directories produced from `docker save` are identical based solely on the directory name.  Neither choice is ideal.

**Comment by marius311** [comment]
Thanks for catching both of these things. The gzip thing should be resolved by https://github.com/marius311/boinc2docker/commit/9d9a32cfc5f5c194ee0c18cd1c97fb7df2c452a5. The other issue I don't think is due to time metadata inside of tar, rather to what I describe in https://github.com/marius311/boinc2docker/issues/8. I will look to fix that as soon as I get a chance.

**Comment by marius311** [comment]
Please feel free to comment / reopen if there's more to discuss here. Closing this in favor of the related issues that still need fixing which are linked in my previous comment.
