### ISSUE TITLE
Change default server name from boincserver.com to 127.0.0.1?

### ISSUE THREAD

**Issue by marius311** [marius311/boinc-server-docker#22]
From @grctest in https://github.com/BOINC/boinc/issues/1990:
> Hey,
> Would it be possible to change the default servername from boincserver.com to 127.0.0.1? When set as boincserver.com it breaks the formatting of the default website view until changed. If set to 127.0.0.1 it would work fine. The domain has also been registered recently so it links offsite.
> Best regards,CM.

**Comment by marius311** [comment]
That's an interesting suggestion. I always hated the need for the extra step of editing `/etc/hosts` and this seems like it would solve it; I had never considered I think outright putting 127.0.0.1 as the project URL. 

I guess one drawback is that if anyone is running the server in docker-machine (such as is necessary on Win/Mac), the right URL isn't 127.0.0.1, its `$(docker-machine ip)` instead. In these cases, the user then needs to reroute 127.0.0.1 port 80 to the docker machine ip instead. I don't know what that looks like on Win/Mac (on Linux its a fairly straightforward `iptables` command) but assuming its no too much worse than editing `/etc/hosts` as was needed before, I do like this solution.

**Comment by marius311** [comment]
(Bigger picture, for this very reason its on my BOINC wishlist for the server to not need to know its URL, but that's more complicated changes to the server code I think)

**Comment by ChristianBeer** [comment]
What about using a `.local` hostname? In the server VM I use a hostname like `debian.local`. The server VM is meant as a starting point for a test project not a production project so it is kind of expected that the admin needs to edit `/etc/hosts` on the host machine in order to connect to the VM. In some cases (like in University networks) one also needs to activate port forwarding to access the webserver in a VM on the host machine.

The reason I use the added `.local` is that the BOINC Manager doesn't accept a short hostname as project URL and checks if there is at least one dot in the given URL.

**Comment by marius311** [comment]
Thanks, another interesting suggestion. I actually think I like `127.0.0.1` more tbh though. On Linux it removes the need to do *anything* after `docker-compose up` to have a 100% functioning server, and on docker-machine it swaps having to edit `/etc/hosts` with having to run `sudo ssh docker@$(docker-machine ip) -L 80:localhost:80 -N`, which is no worse really, so it seems like an overall win to me. There's also a nice consistency with other docker containers where one usually expects to see thing on localhost (e.g. `docker  run -p 80:80 httpd` then you have an apache server on `localhost:80`).

**Comment by marius311** [comment]
This is now implemented in https://github.com/marius311/boinc-server-docker/commit/61aa06db1f9561435079d0e82941af14b107f819 and reflected in the readme/cookbook. Thanks for the idea!
