### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by marius311** [marius311/boinc-server-docker#26]
The default configuration is aimed at getting the server fully functional with no extra steps needed, but leaves the server in a highly insecure state. Somehow this should be improved. Some things which will need consideration:

* mysql password
* ops password
* signing keys
* ???

**Comment by grctest** [comment]
Do you think it'd be appropriate to include by default some security tools to passively monitor the BOINC servers? A couple of the presentations at the BOINC workshop mentioned using such tools. Some may hog system resources though.

Examples:
http://www.chkrootkit.org/
http://rkhunter.sourceforge.net/ (Mentioned during the workshop)
https://www.clamav.net/

**Comment by grctest** [comment]
@marius311 

The following section of the apache dockerfile:
> [libssl1.0.0](https://github.com/marius311/boinc-server-docker/blob/master/images/apache/Dockerfile#L10)

Results in an OpenSSL version:
> OpenSSL 1.0.1k 8 Jan 2015 (Library: OpenSSL 1.0.1t  3 May 2016)

Only noticed when [openssl_sign glitched](https://github.com/BOINC/boinc/pull/2134#discussion_r139643779) recently.

[Advisory notice from OpenSSL](https://www.openssl.org/source/):
>Note: The latest stable version is the 1.1.0 series. The 1.0.2 series is our Long Term Support (LTS) release, supported until 31st December 2019. The 0.9.8, 1.0.0 and ***1.0.1*** versions are now out of support and should not be used.

I think that once users try to implement HTTPS via LetsEncrypt, the server OpenSSL version is uplifted, however the default version is vulnerable and no longer in support.

**Comment by grctest** [comment]
I ran the following tool in my boinc docker dev environment: https://github.com/docker/docker-bench-security

I've filtered out 'PASS' entries, focusing on INFO and WARN messages. Some sections like the host/environment config is only relevant to myself but some of it may be relevant for improving the boinc docker container. I'm also running my pull request version of the dockerfiles.

# INFO 1 - Host Configuration
WARN 1.1  - Ensure a separate partition for containers has been created
NOTE 1.2  - Ensure the container host has been Hardened
INFO 1.3  - Ensure Docker is up to date
INFO      * Using 1.12.6, verify is it up to date as deemed necessary
INFO      * Your operating system vendor may provide support and security maintenance for Docker
INFO 1.4  - Ensure only trusted users are allowed to control Docker daemon
INFO      * docker:x:116:
WARN 1.5  - Ensure auditing is configured for the Docker daemon
WARN 1.6  - Ensure auditing is configured for Docker files and directories - /var/lib/docker
WARN 1.7  - Ensure auditing is configured for Docker files and directories - /etc/docker
WARN 1.8  - Ensure auditing is configured for Docker files and directories - docker.service
WARN 1.9  - Ensure auditing is configured for Docker files and directories - docker.socket
WARN 1.10 - Ensure auditing is configured for Docker files and directories - /etc/default/docker
INFO 1.11 - Ensure auditing is configured for Docker files and directories - /etc/docker/daemon.json
INFO      * File not found
INFO 1.12 - Ensure auditing is configured for Docker files and directories - /usr/bin/docker-containerd
INFO      * File not found
INFO 1.13 - Ensure auditing is configured for Docker files and directories - /usr/bin/docker-runc
INFO      * File not found

# INFO 2 - Docker daemon configuration
WARN 2.1  - Ensure network traffic is restricted between containers on the default bridge
WARN 2.5  - Ensure aufs storage driver is not used
INFO 2.6  - Ensure TLS authentication for Docker daemon is configured
INFO      * Docker daemon not listening on TCP
INFO 2.7  - Ensure the default ulimit is configured appropriately
INFO      * Default ulimit doesn't appear to be set
WARN 2.8  - Enable user namespace support
WARN 2.11 - Ensure that authorization for Docker client commands is enabled
WARN 2.13 - Ensure operations on legacy registry (v1) are Disabled
WARN 2.14 - Ensure live restore is Enabled
WARN 2.15 - Ensure Userland Proxy is Disabled
INFO 2.16 - Ensure daemon-wide custom seccomp profile is applied, if needed

# INFO 3 - Docker daemon configuration files
INFO 3.7  - Ensure that registry certificate file ownership is set to root:root
INFO      * Directory not found
INFO 3.8  - Ensure that registry certificate file permissions are set to 444 or more restrictive
INFO      * Directory not found
INFO 3.9  - Ensure that TLS CA certificate file ownership is set to root:root
INFO      * No TLS CA certificate found
INFO 3.10 - Ensure that TLS CA certificate file permissions are set to 444 or more restrictive
INFO      * No TLS CA certificate found
INFO 3.11 - Ensure that Docker server certificate file ownership is set to root:root
INFO      * No TLS Server certificate found
INFO 3.12 - Ensure that Docker server certificate file permissions are set to 444 or more restrictive
INFO      * No TLS Server certificate found
INFO 3.13 - Ensure that Docker server certificate key file ownership is set to root:root
INFO      * No TLS Key found
INFO 3.14 - Ensure that Docker server certificate key file permissions are set to 400
INFO      * No TLS Key found
INFO 3.17 - Ensure that daemon.json file ownership is set to root:root
INFO      * File not found
INFO 3.18 - Ensure that daemon.json file permissions are set to 644 or more restrictive
INFO      * File not found

# INFO 4 - Container Images and Build File
WARN 4.1  - Ensure a user for the container has been created
WARN      * Running as root: boincserverdocker_apache_1
WARN      * Running as root: boincserverdocker_mysql_1
NOTE 4.2  - Ensure that containers use trusted base images
NOTE 4.3  - Ensure unnecessary packages are not installed in the container
NOTE 4.4  - Ensure images are scanned and rebuilt to include security patches
WARN 4.5  - Ensure Content trust for Docker is Enabled
WARN 4.6  - Ensure HEALTHCHECK instructions have been added to the container image
WARN      * No Healthcheck found: [boinc/server_makeproject:latest-b2d]
WARN      * No Healthcheck found: [boinc/server_mysql:latest]
WARN      * No Healthcheck found: [boinc/server_apache:latest-b2d]
WARN      * No Healthcheck found: [mysql:5.7.19]
WARN      * No Healthcheck found: [php:5.6.31-apache]
WARN      * No Healthcheck found: [debian:jessie]
WARN      * No Healthcheck found: [php:5.6.17-apache]
WARN      * No Healthcheck found: [mysql:5.7.10]
INFO 4.7  - Ensure update instructions are not use alone in the Dockerfile
INFO      * Update instruction found: [boinc/server_makeproject:latest-b2d]
INFO      * Update instruction found: [boinc/server_mysql:latest]
INFO      * Update instruction found: [boinc/server_apache:latest-b2d]
INFO      * Update instruction found: [mysql:5.7.19]
INFO      * Update instruction found: [php:5.6.31-apache]
INFO      * Update instruction found: [php:5.6.17-apache]
INFO      * Update instruction found: [mysql:5.7.10]
NOTE 4.8  - Ensure setuid and setgid permissions are removed in the images
INFO 4.9  - Ensure COPY is used instead of ADD in Dockerfile
INFO      * ADD in image history: [boinc/server_makeproject:latest-b2d]
INFO      * ADD in image history: [boinc/server_mysql:latest]
INFO      * ADD in image history: [boinc/server_apache:latest-b2d]
INFO      * ADD in image history: [mysql:5.7.19]
INFO      * ADD in image history: [php:5.6.31-apache]
INFO      * ADD in image history: [debian:jessie]
INFO      * ADD in image history: [php:5.6.17-apache]
INFO      * ADD in image history: [mysql:5.7.10]
NOTE 4.10 - Ensure secrets are not stored in Dockerfiles
NOTE 4.11 - Ensure verified packages are only Installed


# INFO 5 - Container Runtime
WARN 5.1  - Ensure AppArmor Profile is Enabled
WARN      * No AppArmorProfile Found: boincserverdocker_apache_1
WARN      * No AppArmorProfile Found: boincserverdocker_mysql_1
WARN 5.2  - Ensure SELinux security options are set, if applicable
WARN      * No SecurityOptions Found: boincserverdocker_apache_1
WARN      * No SecurityOptions Found: boincserverdocker_mysql_1
WARN 5.7  - Ensure privileged ports are not mapped within containers
WARN      * Privileged Port in use: 80 in boincserverdocker_apache_1
NOTE 5.8  - Ensure only needed ports are open on the container
WARN 5.10 - Ensure memory usage for container is limited
WARN      * Container running without memory restrictions: boincserverdocker_apache_1
WARN      * Container running without memory restrictions: boincserverdocker_mysql_1
WARN 5.11 - Ensure CPU priority is set appropriately on the container
WARN      * Container running without CPU restrictions: boincserverdocker_apache_1
WARN      * Container running without CPU restrictions: boincserverdocker_mysql_1
WARN 5.12 - Ensure the container's root filesystem is mounted as read only
WARN      * Container running with root FS mounted R/W: boincserverdocker_apache_1
WARN      * Container running with root FS mounted R/W: boincserverdocker_mysql_1
WARN 5.13 -  Ensure incoming container traffic is binded to a specific host interface
WARN      * Port being bound to wildcard IP: 0.0.0.0 in boincserverdocker_apache_1
WARN 5.14 - Ensure 'on-failure' container restart policy is set to '5'
WARN      * MaximumRetryCount is not set to 5: boincserverdocker_apache_1
WARN      * MaximumRetryCount is not set to 5: boincserverdocker_mysql_1
INFO 5.18 - Ensure the default ulimit is overwritten at runtime, only if needed
INFO      * Container no default ulimit override: boincserverdocker_apache_1
INFO      * Container no default ulimit override: boincserverdocker_mysql_1
NOTE 5.22 - Ensure docker exec commands are not used with privileged option
NOTE 5.23 - Ensure docker exec commands are not used with user option
WARN 5.25 - Ensure the container is restricted from acquiring additional privileges
WARN      * Privileges not restricted: boincserverdocker_apache_1
WARN      * Privileges not restricted: boincserverdocker_mysql_1
WARN 5.26 - Ensure container health is checked at runtime
WARN      * Health check not set: boincserverdocker_apache_1
WARN      * Health check not set: boincserverdocker_mysql_1
INFO 5.27 - Ensure docker commands always get the latest version of the image
WARN 5.28 - Ensure PIDs cgroup limit is used
WARN      * PIDs limit not set: boincserverdocker_apache_1
WARN      * PIDs limit not set: boincserverdocker_mysql_1
INFO 5.29 - Ensure Docker's default bridge docker0 is not used
INFO      * Container in docker0 network: boincserverdocker_apache_1
INFO      * Container in docker0 network: 
WARN 5.31 - Ensure the Docker socket is not mounted inside any containers
WARN      * Docker socket shared: boincserverdocker_apache_1

# INFO 6 - Docker Security Operations
INFO 6.1  - Avoid image sprawl
INFO      * There are currently: 43 images
INFO      * Only 16 out of 43 are in use
INFO 6.2  - Avoid container sprawl
INFO      * There are currently a total of 16 containers, with 2 of them currently running
