### ISSUE TITLE
Handle large docker images

### ISSUE THREAD

**Issue by zonca** [marius311/boinc-server-docker#34]
I currently have a very large docker image to run my application, it is ~1GB uncompressed,
I'm trying to reduce it further but for now I'd like to make some tests as is.

I see that my BOINC jobs go out of disk space when uncompressing the layers.
Where can I increase space of the images so that this is able to run?

**Comment by davidpanderson** [comment]
Set the jobs' rsc_disk_bound (in the input template, or as an arg to create_work)
to a value of at least the actual disk usage, including the uncompressed docker image.
Then the jobs will only be sent to hosts with adequate disk space.

**Comment by marius311** [comment]
What's the error message on host? Nominally boinc2docker_create_work [automatically picks](https://github.com/marius311/boinc2docker/blob/b2e3baa4aa0c790a06ab8b987b908fca8f846ac7/bin/boinc2docker_create_work.py#L302-L315) a disk size which is the size of the uncompressed image + 100Mb, maybe something about that logic is failing? 

Also, worth mentioning, if you use `native_unzip=False`(the default), then the image files are unzipped inside the VM, and since the VM uses a RAM disk, then the disk space necessary is only the compressed image size, but the *memory* requirement ends up becoming 3 * the uncompressed image size since the decompression happens in the RAM disk (the factor 3 because of various temp files that get stored during decompression / docker import). Nominally these should all be set automatically. 

In any case, `rsc_disk_bound` (and `rsc_memory_bound`) as David mentions are options to boinc2docker_create_work so you can always set stuff by hand.

**Comment by marius311** [comment]
You might also be interested in https://github.com/marius311/stfd which I use on the C@H images. it results in a pretty drastic reduction in image size (although as a side-effect it squashes everything into one layer so you loose the nice quality that common base layers aren't reuploaded to clients). I haven't checked this is ~year so its possible some Docker updates broke it though, let me know if you try it and if that did indeed happen.
