### ISSUE TITLE
Error when first running docker-compose up.

### ISSUE THREAD

**Issue by NeuralMiner** [marius311/boinc-server-docker#9]
When first running `docker-compose up -d` (under Launching a Test Server), I get the following error:

Step 4 : COPY boinc /root/boinc
 ---> Using cache
 ---> 4f5638c0af7b
Step 5 : RUN cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make
 ---> Running in b7e087519886
**/bin/sh: 1: ./_autosetup: not found
ERROR: Service 'makeproject' failed to build: The command '/bin/sh -c cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make' returned a non-zero code: 127**

I'm able to get past it by running `docker-compose pull` followed by `docker-compose up`.

_Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux_

**Comment by MTRNord** [comment]
Did you pull the repo with `git pull --recursive`?

**Comment by lionelca** [comment]
Hello 
I had same issue than NeuralMiner using git clone https://github.com/marius311/boinc-server-docker.git 
 (boinc directory was empty)

I have tested git clone --recursive https://github.com/marius311/boinc-server-docker.git

Everything is working fine until : 
 
Step 5 : RUN cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make
 ---> Running in 86884f9a5dca
[91m/bin/sh: 1: ./_autosetup: Permission denied
[0m[31mERROR[0m: Service 'makeproject' failed to build: The command '/bin/sh -c cd /root/boinc && ./_autosetup && ./configure --disable-client --disable-manager && make' returned a non-zero code: 126


Windows 10 Pro-Intel Core i7

**Comment by MTRNord** [comment]
I am not shure but maybe it uses the old docker images. Is the error still there if you remove these Images?

**Comment by marius311** [comment]
Correct, I believe cloning with `--recursive` to get the submodules will solve @NeuralMiner's original problem. 

@lionelca, your problem is related to running Docker on Windows (presumably you're using Docker Toolbox?). I've seen the same thing before. I don't fully understand what's going on yet. Let me create an Issue to track this problem properly. Two possible workarounds until its fixed:

* Actually, if all you're looking to do is create your own project, then you don't need to build any of the boinc-server-docker images yourself, you can pull them from the Hub and build your own project on top of them as described in the (albeit very work-in-progress) [cookbook](https://github.com/marius311/boinc-server-docker/blob/master/docs/cookbook.md).

* Assuming I'm right that you're using Docker Toolbox, and if you meet the requirements, you might try [Docker for Windows](https://docs.docker.com/docker-for-windows/). Maybe that works better.

**Comment by NeuralMiner** [comment]
Sure enough, `--recursive` fixed it for me.

**Comment by marius311** [comment]
Great, I'll close this and keep https://github.com/marius311/boinc-server-docker/issues/10 open to track the permission error.
